# Generated by Django 3.2.5 on 2021-10-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=16)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=12)),
                ('lessons', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=6)),
                ('courses', models.CharField(max_length=17)),
                ('company', models.CharField(max_length=15)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('resume', models.FileField(upload_to='')),
                ('contract', models.FileField(upload_to='')),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda')], max_length=8)),
                ('nationality', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Rwandese', 'Rwandese'), ('Ugandan', 'Ugandan'), ('Sudanese', 'Sudanese'), ('South Sudanese', 'South Sudanese'), ('Somalia', 'Somalia')], max_length=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=8, null=True)),
            ],
        ),
    ]
