# Generated by Django 3.2.5 on 2021-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='e.g. Sandra', max_length=20)),
                ('last_name', models.CharField(max_length=16)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('student_id', models.CharField(max_length=12)),
                ('student_class', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_name', models.CharField(max_length=14)),
                ('parent_phone', models.CharField(max_length=13)),
                ('passport', models.CharField(blank=True, max_length=15, null=True)),
                ('mentor', models.CharField(max_length=10, null=True)),
                ('room_number', models.CharField(blank=True, max_length=3, null=True)),
                ('laptop_number', models.CharField(blank=True, max_length=10, null=True)),
                ('big_sister', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda')], max_length=8)),
                ('nationality', models.CharField(choices=[('Kenyan', 'Kenyan'), ('Rwandese', 'Rwandese'), ('Ugandan', 'Ugandan'), ('Sudanese', 'Sudanese'), ('South Sudanese', 'South Sudanese'), ('Somalia', 'Somalia')], max_length=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=8, null=True)),
            ],
        ),
    ]
